// src/app/layout.tsx
"use client"; // Add double quotes

import { Metadata } from "next";
import "./globals.css";


import { AnimatePresence } from "framer-motion";

const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
                <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons" />

      <body>
        <AnimatePresence mode="wait">
          {children}
        </AnimatePresence>
        
      </body>
    </html>
  );
}
